from typing import Protocol, Optional, Any, runtime_checkable
from pydantic import BaseModel, Field


class ElementRect(BaseModel):
    x: float
    y: float
    width: float
    height: float


class InteractionPolicy(BaseModel):
    min_action_interval_ms: int = 150
    action_timeout_ms: int = 10000
    max_retries: int = 3


@runtime_checkable
class BrowserElement(Protocol):
    async def get_attribute(self, name: str) -> Optional[str]: ...
    async def get_text(self) -> str: ...
    async def inspect_field(self) -> dict[str, Any]: ...
    async def is_checked(self) -> bool: ...
    async def click(self) -> None: ...
    async def type_text(self, text: str) -> None: ...
    async def clear_text(self) -> None: ...
    async def select_option(self, value: str) -> None: ...
    async def set_files(self, file_paths: list[str]) -> None: ...
    async def get_bounding_rect(self) -> ElementRect: ...
    async def scroll_into_view(self) -> None: ...


@runtime_checkable
class BrowserPage(Protocol):
    async def url(self) -> str: ...
    async def title(self) -> str: ...
    async def find(self, selector: str) -> Optional[BrowserElement]: ...
    async def find_all(self, selector: str) -> list[BrowserElement]: ...
    async def wait_for(self, selector: str, timeout_ms: int = 5000) -> BrowserElement: ...
    async def execute_unsafe_script(self, reason: str, script: str, arg: Any = None) -> Any: ...


@runtime_checkable
class BrowserBackend(Protocol):
    async def open_page(self, url: str) -> BrowserPage: ...
    async def current_page(self) -> BrowserPage: ...
    async def wait_for_user(self, reason: str) -> None: ...
    async def close(self) -> None: ...
